json.netCal(@net_cal)
json.carbs(@carbs)
json.fats(@fats)
json.protein(@protein)
json.calsBurned(@cals_burned)
json.(@profile, :workouts_per_week, :mins_per_workout)
json.bmr(@BMR)
json.calDeficit(@cal_deficit)
json.projectedLoss(@projected_loss)