json.pageId(@page.id)
json.entryDate(@entry_date)
json.breakfasts(@breakfasts)

json.totalLunchCals(@total_lunch_cals)
json.totalLunchCarbs(@total_lunch_carbs)
json.totalLunchFat(@total_lunch_fat)
json.totalLunchProtein(@total_lunch_protein)
json.totalLunchSodium(@total_lunch_sodium)
json.totalLunchSugar(@total_lunch_sugar)

json.totalDinnerCals(@total_dinner_cals)
json.totalDinnerCarbs(@total_dinner_carbs)
json.totalDinnerFat(@total_dinner_fat)
json.totalDinnerProtein(@total_dinner_protein)
json.totalDinnerSodium(@total_dinner_sodium)
json.totalDinnerSugar(@total_dinner_sugar)

json.totalBreakfastCals(@total_breakfast_cals)
json.totalBreakfastCarbs(@total_breakfast_carbs)
json.totalBreakfastFat(@total_breakfast_fat)
json.totalBreakfastProtein(@total_breakfast_protein)
json.totalBreakfastSodium(@total_breakfast_sodium)
json.totalBreakfastSugar(@total_breakfast_sugar)

json.totalSnackCals(@total_snack_cals)
json.totalSnackCarbs(@total_snack_carbs)
json.totalSnackFat(@total_snack_fat)
json.totalSnackProtein(@total_snack_protein)
json.totalSnackSodium(@total_snack_sodium)
json.totalSnackSugar(@total_snack_sugar)

json.totalCals(@total_cals)
json.totalCarbs(@total_carbs)
json.totalFat(@total_fat)
json.totalProtein(@total_protein)
json.totalSodium(@total_sodium)
json.totalSugar(@total_sugar)

json.targetCals(@target_cals)
json.targetCarbs(@target_carbs)
json.targetFat(@target_fats)
json.targetProtein(@target_protein)
json.targetSodium(@target_sodium)
json.targetSugar(@target_sugar)


